// Generated by the FlutterFire CLI (`flutterfire configure`) against the
// real, hosted `taakrak-d9ed0` Firebase project — these are live values,
// not a placeholder. They're safe to commit: a Firebase client config
// (unlike a server API key) only identifies which project to talk to;
// access itself is enforced by firestore.rules and Firebase Auth, not by
// keeping this file secret. A clone of this repo talks to the same
// project out of the box, with no setup required. Only re-run
// `flutterfire configure` if you deliberately want to point the app at a
// different Firebase project — it will overwrite this file with new
// values.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this '
          'platform. Run `flutterfire configure` to generate them.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebdNwcTIYPJ9b288C7ztn6bjZwe_yag8',
    appId: '1:329351564706:web:c8f6216f0af1f8bb1776fb',
    messagingSenderId: '329351564706',
    projectId: 'taakrak-d9ed0',
    authDomain: 'taakrak-d9ed0.firebaseapp.com',
    storageBucket: 'taakrak-d9ed0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc7-SdIyCg_-IXC6N41ADPXfmbmF6d-g8',
    appId: '1:329351564706:android:65cf6f85c08df2c81776fb',
    messagingSenderId: '329351564706',
    projectId: 'taakrak-d9ed0',
    storageBucket: 'taakrak-d9ed0.firebasestorage.app',
  );
}
